trigger:
  - '*'

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: Build
    steps:
      - task: Gradle@2
        displayName: Run Gradle Build
        inputs:
          workingDirectory: ''
          gradleWrapperFile: 'gradlew'
          gradleOptions: '-Xmx3072m'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.11'
          jdkArchitectureOption: 'x64'
          publishJUnitResults: true
          testResultsFiles: '**/TEST-*.xml'
          tasks: 'clean check assemble'
          codeCoverageToolOption: 'jaCoCo'
          checkStyleRunAnalysis: true
      - task: PublishPipelineArtifact@1
        displayName: Publish App Archive
        inputs:
          path: $(System.DefaultWorkingDirectory)/build/libs
          artifact: AppJar
